[
  {
    "Book Id": 154278,
    "Title": "Fractal Market Analysis: Applying Chaos Theory to Investment and Economics",
    "Author": "Edgar E. Peters",
    "Author l-f": "Peters, Edgar E.",
    "Additional Authors": "",
    "ISBN": "=\"0471585246",
    "ISBN13": "=\"9780471585244",
    "My Rating": 0,
    "Average Rating": 3.33,
    "Publisher": "Wiley",
    "Binding": "Hardcover",
    "Number of Pages": 336,
    "Year Published": 1994,
    "Original Publication Year": 1994,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "to-read",
    "Bookshelves with positions": "to-read (#16)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Owned Copies": 0
  },
  {
    "Book Id": 665134,
    "Title": "The (Mis)Behavior of Markets",
    "Author": "Benoît B. Mandelbrot",
    "Author l-f": "Mandelbrot, Benoît B.",
    "Additional Authors": "Richard L. Hudson",
    "ISBN": "=\"0465043550",
    "ISBN13": "=\"9780465043552",
    "My Rating": 0,
    "Average Rating": 4.09,
    "Publisher": "Basic Books",
    "Binding": "Hardcover",
    "Number of Pages": 352,
    "Year Published": 2004,
    "Original Publication Year": 1997,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "to-read",
    "Bookshelves with positions": "to-read (#15)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Owned Copies": 0
  },
  {
    "Book Id": 1590178,
    "Title": "The Evolution of Nuclear Strategy",
    "Author": "Lawrence Freedman",
    "Author l-f": "Freedman, Lawrence",
    "Additional Authors": "",
    "ISBN": "=\"0333972392",
    "ISBN13": "=\"9780333972397",
    "My Rating": 0,
    "Average Rating": 4.11,
    "Publisher": "see notes for publisher info",
    "Binding": "Paperback",
    "Number of Pages": 584,
    "Year Published": 2003,
    "Original Publication Year": 1981,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "to-read",
    "Bookshelves with positions": "to-read (#14)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Owned Copies": 0
  },
  {
    "Book Id": 18555040,
    "Title": "The Direction of War: Contemporary Strategy in Historical Perspective",
    "Author": "Hew Strachan",
    "Author l-f": "Strachan, Hew",
    "Additional Authors": "",
    "ISBN": "=\"1107047854",
    "ISBN13": "=\"9781107047853",
    "My Rating": 0,
    "Average Rating": 4.17,
    "Publisher": "Cambridge University Press",
    "Binding": "Hardcover",
    "Number of Pages": 338,
    "Year Published": 2014,
    "Original Publication Year": 2013,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "to-read",
    "Bookshelves with positions": "to-read (#13)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Owned Copies": 0
  },
  {
    "Book Id": 17847473,
    "Title": "Strategy: A History",
    "Author": "Lawrence Freedman",
    "Author l-f": "Freedman, Lawrence",
    "Additional Authors": "",
    "ISBN": "=\"0199325154",
    "ISBN13": "=\"9780199325153",
    "My Rating": 0,
    "Average Rating": 3.98,
    "Publisher": "Oxford University Press",
    "Binding": "Hardcover",
    "Number of Pages": 768,
    "Year Published": 2013,
    "Original Publication Year": 2013,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "to-read",
    "Bookshelves with positions": "to-read (#12)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Owned Copies": 0
  },
  {
    "Book Id": 1051121,
    "Title": "Modern Strategy",
    "Author": "Colin S. Gray",
    "Author l-f": "Gray, Colin S.",
    "Additional Authors": "",
    "ISBN": "=\"0198782519",
    "ISBN13": "=\"9780198782513",
    "My Rating": 0,
    "Average Rating": 4.03,
    "Publisher": "Oxford University Press",
    "Binding": "Paperback",
    "Number of Pages": 426,
    "Year Published": 1999,
    "Original Publication Year": 1999,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "to-read",
    "Bookshelves with positions": "to-read (#11)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Owned Copies": 0
  },
  {
    "Book Id": 55300,
    "Title": "Napoleon: A Life",
    "Author": "Paul  Johnson",
    "Author l-f": "Johnson, Paul",
    "Additional Authors": "",
    "ISBN": "=\"0143037455",
    "ISBN13": "=\"9780143037453",
    "My Rating": 0,
    "Average Rating": 3.66,
    "Publisher": "Penguin Publishing Group",
    "Binding": "Paperback",
    "Number of Pages": 208,
    "Year Published": 2006,
    "Original Publication Year": 2002,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "to-read",
    "Bookshelves with positions": "to-read (#10)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Owned Copies": 0
  },
  {
    "Book Id": 22017921,
    "Title": "Carl Von Clausewitz on War",
    "Author": "Anatol Rapoport",
    "Author l-f": "Rapoport, Anatol",
    "Additional Authors": "",
    "ISBN": "=\"",
    "ISBN13": "=\"",
    "My Rating": 0,
    "Average Rating": 3.79,
    "Publisher": "Penguin Books",
    "Binding": "Hardcover",
    "Number of Pages": "",
    "Year Published": "",
    "Original Publication Year": "",
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "to-read",
    "Bookshelves with positions": "to-read (#9)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Owned Copies": 0
  },
  {
    "Book Id": 40718726,
    "Title": "Genghis Khan and the Making of the Modern World",
    "Author": "Jack Weatherford",
    "Author l-f": "Weatherford, Jack",
    "Additional Authors": "",
    "ISBN": "=\"",
    "ISBN13": "=\"",
    "My Rating": 0,
    "Average Rating": 4.06,
    "Publisher": "Broadway Books",
    "Binding": "Kindle Edition",
    "Number of Pages": 352,
    "Year Published": 2018,
    "Original Publication Year": 2004,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "to-read",
    "Bookshelves with positions": "to-read (#8)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Owned Copies": 0
  },
  {
    "Book Id": 10534,
    "Title": "The Art of War",
    "Author": "Sun Tzu",
    "Author l-f": "Tzu, Sun",
    "Additional Authors": "Thomas Cleary",
    "ISBN": "=\"",
    "ISBN13": "=\"",
    "My Rating": 0,
    "Average Rating": 3.95,
    "Publisher": "Harper Press",
    "Binding": "Paperback",
    "Number of Pages": 170,
    "Year Published": 2005,
    "Original Publication Year": -400,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "to-read",
    "Bookshelves with positions": "to-read (#7)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Owned Copies": 0
  },
  {
    "Book Id": 867247,
    "Title": "A Book of Five Rings: The Classic Guide to Strategy",
    "Author": "Miyamoto Musashi",
    "Author l-f": "Musashi, Miyamoto",
    "Additional Authors": "Victor Harris, Lew Hartman",
    "ISBN": "=\"0517415283",
    "ISBN13": "=\"9780517415283",
    "My Rating": 0,
    "Average Rating": 3.96,
    "Publisher": "Gramercy",
    "Binding": "Hardcover",
    "Number of Pages": 192,
    "Year Published": 1988,
    "Original Publication Year": 1645,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "to-read",
    "Bookshelves with positions": "to-read (#6)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Owned Copies": 0
  },
  {
    "Book Id": 55030,
    "Title": "Cosmos",
    "Author": "Carl Sagan",
    "Author l-f": "Sagan, Carl",
    "Additional Authors": "",
    "ISBN": "=\"0375508325",
    "ISBN13": "=\"9780375508325",
    "My Rating": 0,
    "Average Rating": 4.4,
    "Publisher": "Random House",
    "Binding": "Mass Market Paperback",
    "Number of Pages": 384,
    "Year Published": 2002,
    "Original Publication Year": 1980,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "to-read",
    "Bookshelves with positions": "to-read (#5)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Owned Copies": 0
  },
  {
    "Book Id": 56643989,
    "Title": "Life Is Simple: How Occam's Razor Set Science Free and Shapes the Universe",
    "Author": "Johnjoe McFadden",
    "Author l-f": "McFadden, Johnjoe",
    "Additional Authors": "",
    "ISBN": "=\"1541620445",
    "ISBN13": "=\"9781541620445",
    "My Rating": 0,
    "Average Rating": 3.94,
    "Publisher": "Basic Books",
    "Binding": "Hardcover",
    "Number of Pages": 384,
    "Year Published": 2021,
    "Original Publication Year": 2021,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "to-read",
    "Bookshelves with positions": "to-read (#4)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Owned Copies": 0
  },
  {
    "Book Id": 5877139,
    "Title": "Chaotic Dynamics: Theory and Applications to Economics",
    "Author": "Alfredo Medio",
    "Author l-f": "Medio, Alfredo",
    "Additional Authors": "Giampaolo Gallo",
    "ISBN": "=\"0521484618",
    "ISBN13": "=\"9780521484619",
    "My Rating": 0,
    "Average Rating": 0,
    "Publisher": "Cambridge University Press",
    "Binding": "Paperback",
    "Number of Pages": 364,
    "Year Published": 1995,
    "Original Publication Year": 1993,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "to-read",
    "Bookshelves with positions": "to-read (#3)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Owned Copies": 0
  },
  {
    "Book Id": 208219318,
    "Title": "Chaos Theory in Psychology (Contributions in Psychology) by Abraham Fred Gilgen Albert R. (1995-04-25) Paperback",
    "Author": "unknown author",
    "Author l-f": "author, unknown",
    "Additional Authors": "",
    "ISBN": "=\"",
    "ISBN13": "=\"",
    "My Rating": 0,
    "Average Rating": 0,
    "Publisher": "",
    "Binding": "Paperback",
    "Number of Pages": "",
    "Year Published": "",
    "Original Publication Year": "",
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "to-read",
    "Bookshelves with positions": "to-read (#2)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Owned Copies": 0
  },
  {
    "Book Id": 2531540,
    "Title": "Quantum Chaos: An Introduction: An Introduction",
    "Author": "Hans-Jürgen Stöckmann",
    "Author l-f": "Stöckmann, Hans-Jürgen",
    "Additional Authors": "",
    "ISBN": "=\"0521027152",
    "ISBN13": "=\"9780521027151",
    "My Rating": 0,
    "Average Rating": 4,
    "Publisher": "Cambridge University Press",
    "Binding": "Paperback",
    "Number of Pages": 384,
    "Year Published": 2008,
    "Original Publication Year": 1999,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "to-read",
    "Bookshelves with positions": "to-read (#1)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Owned Copies": 0
  },
  {
    "Book Id": 1842,
    "Title": "Guns, Germs, and Steel: The Fates of Human Societies",
    "Author": "Jared Diamond",
    "Author l-f": "Diamond, Jared",
    "Additional Authors": "",
    "ISBN": "=\"0739467352",
    "ISBN13": "=\"9780739467350",
    "My Rating": 5,
    "Average Rating": 4.04,
    "Publisher": "W.W. Norton & Company",
    "Binding": "Paperback",
    "Number of Pages": 498,
    "Year Published": 2005,
    "Original Publication Year": 1997,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "",
    "Bookshelves with positions": "",
    "Exclusive Shelf": "read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 1,
    "Owned Copies": 0
  },
  {
    "Book Id": 54614037,
    "Title": "The God Equation: The Quest for a Theory of Everything",
    "Author": "Michio Kaku",
    "Author l-f": "Kaku, Michio",
    "Additional Authors": "",
    "ISBN": "=\"0385542747",
    "ISBN13": "=\"9780385542746",
    "My Rating": 5,
    "Average Rating": 4.11,
    "Publisher": "Doubleday",
    "Binding": "Hardcover",
    "Number of Pages": 225,
    "Year Published": 2021,
    "Original Publication Year": 2021,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "",
    "Bookshelves with positions": "",
    "Exclusive Shelf": "read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 1,
    "Owned Copies": 0
  },
  {
    "Book Id": 3438171,
    "Title": "A Philosophical Essay on Probabilities (Dover Books on Mathematics)",
    "Author": "Pierre-Simon Laplace",
    "Author l-f": "Laplace, Pierre-Simon",
    "Additional Authors": "",
    "ISBN": "=\"0486288757",
    "ISBN13": "=\"9780486288758",
    "My Rating": 4,
    "Average Rating": 3.97,
    "Publisher": "Dover Publications",
    "Binding": "Paperback",
    "Number of Pages": 224,
    "Year Published": 1996,
    "Original Publication Year": 1994,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "",
    "Bookshelves with positions": "",
    "Exclusive Shelf": "read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 1,
    "Owned Copies": 0
  },
  {
    "Book Id": 64582,
    "Title": "Chaos: Making a New Science",
    "Author": "James Gleick",
    "Author l-f": "Gleick, James",
    "Additional Authors": "",
    "ISBN": "=\"0140092501",
    "ISBN13": "=\"9780140092509",
    "My Rating": 5,
    "Average Rating": 4.04,
    "Publisher": "Penguin Group",
    "Binding": "Paperback",
    "Number of Pages": 352,
    "Year Published": 1988,
    "Original Publication Year": 1987,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "",
    "Bookshelves with positions": "",
    "Exclusive Shelf": "read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 1,
    "Owned Copies": 0
  }
]
