// JSON exportado do Goodreads
const booksData = [
  {
    "Book Id": 154278,
    "Title": "Fractal Market Analysis: Applying Chaos Theory to Investment and Economics",
    "Author": "Edgar E. Peters",
    "Author l-f": "Peters, Edgar E.",
    "Additional Authors": "",
    "ISBN": "=\"0471585246",
    "ISBN13": "=\"9780471585244",
    "My Rating": 0,
    "Average Rating": 3.33,
    "Publisher": "Wiley",
    "Binding": "Hardcover",
    "Number of Pages": 336,
    "Year Published": 1994,
    "Original Publication Year": 1994,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "to-read",
    "Bookshelves with positions": "to-read (#16)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Owned Copies": 0
  },
  {
    "Book Id": 665134,
    "Title": "The (Mis)Behavior of Markets",
    "Author": "Benoît B. Mandelbrot",
    "Author l-f": "Mandelbrot, Benoît B.",
    "Additional Authors": "Richard L. Hudson",
    "ISBN": "=\"0465043550",
    "ISBN13": "=\"9780465043552",
    "My Rating": 0,
    "Average Rating": 4.09,
    "Publisher": "Basic Books",
    "Binding": "Hardcover",
    "Number of Pages": 352,
    "Year Published": 2004,
    "Original Publication Year": 1997,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "to-read",
    "Bookshelves with positions": "to-read (#15)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Owned Copies": 0
  },
  {
    "Book Id": 1590178,
    "Title": "The Evolution of Nuclear Strategy",
    "Author": "Lawrence Freedman",
    "Author l-f": "Freedman, Lawrence",
    "Additional Authors": "",
    "ISBN": "=\"0333972392",
    "ISBN13": "=\"9780333972397",
    "My Rating": 0,
    "Average Rating": 4.11,
    "Publisher": "see notes for publisher info",
    "Binding": "Paperback",
    "Number of Pages": 584,
    "Year Published": 2003,
    "Original Publication Year": 1981,
    "Date Read": "",
    "Date Added": "2025/02/25",
    "Bookshelves": "to-read",
    "Bookshelves with positions": "to-read (#14)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Owned Copies": 0
  },
  {
    "Book Id": 18555040,
    "Title": "The Direction of War: Contemporary Strategy in Historical Perspective",
    "Author": "Hew Strachan",
    "Author l-f": "Strachan, Hew",
    "Additional Authors": "",
    "ISBN": "=\"1107047854",
    "ISBN13": "=\"978110
